spring:
  datasource:
    url: jdbc:sqlserver://database-server-ps.database.windows.net:1433;database=DatabasePS;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: pankaj
    password: Nagarro@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


